
<!--Start footer-->
<div class="footer">
    <div class="container">
        Copyright &copy; 2018 Focal
        <div class="font">
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-linkedin-in"></i></a>
        </div>
    </div>
</div>
<!--End footer-->

<script src="layout/js/jquery-3.3.1.min.js"></script>
<script src="layout/js/popper.min.js"></script>
<script src="layout/js/bootstrap.bundle.min.js"></script>
<script src="layout/js/all.min.js"></script>
<script src="layout/js/wow.js"></script>
<script>new WOW().init();</script>
<script src="layout/js/main.js"></script>
</body>
</html>